### ISSUE TITLE
Feature Request Android- "Mock Location"

### ISSUE THREAD

**Issue by Jpersh27** [ivpn/android-app#14]
-Hello @AlexKorvin @jurajhilje I have another feature request for the Android version of IVPN if you don't mind.

1.) Is there any plans to utilize or introduce the Mock Location feature under Android Developer Settings?

-If a feature such as GPS Override ("Mock Location") is supported and enabled within the IVPN application. 
-Any app on your Android device that requests access to your physical coordinates will be overridden by the coordinates of a selected VPN server when in use.

-For example, say a user is physically located in the USA and is connected to one of IVPN's servers in Switzerland. Whenever any app on there Android device asks for their location it will now receive the location of the VPN server in Switzerland as opposed to their actual GPS location in the USA. 

-One current and well known vpn service called ''Surf Shark" offers this feature already, and it already works on there Android version of there VPN application. I tested there service and utilized this feature and it was easy to enable under developer options. They included easy to follow step by step instructions how to enable the feature.

-I used it on two diffrent Android phones and two diffrent versions of Android. Versions being Android 9 pie and Android 10 Q. The feature worked seamlessly and didn't leak my location ever, and matched the same location of the server I was connected too. 

-Overall I think its a useful feature and better then having to use a third party app alongside your vpn to spoof your GPS Location.

-Thank you and I hope I explained everything well enough. I hope to hear back from someone here soon.

**Comment by AlexKorvin** [comment]
@Jpersh27 Thank you for the nice feature request. We added it to our backlog.

**Comment by gorkapernas** [comment]
Verified on version 2.4.0, Samsung G S10/Android 11 and Huawei MediPad T5/Android 8, the "mock location" feature has been implemented and mostly works as expected, when enabled, the mock location matches the VPN location and overrides the GPS's real location. When disconnecting from the VPN, the real location is used instead.
Tested with OpenVPN Single and MultiHop and WireGuard.

@AlexKorvin there is one issue, when disabling "Mock Location" and relaunching the app, the "Mock Location" appears enabled, although the GPS uses the real location when connecting to the VPN, so it seems to be a UI issue with the toggle. Can you check this?

Steps:
- Enable "Mock Location" in the IVPN app and device settings.
- Disable "Mock Location" in the IVPN app (turn the toggle off)
- Close the IVPN app
- Launch the IVPN app
- Observe that "Mock Location" is enabled

**Comment by gorkapernas** [comment]
Verified on version 2.4.0_beta5, the issue raised in my previous comment has been fixed. The "Mock Location" toggle remains off after relaunching the app. 

There was another issue which has also been fixed on this version, the tutorial screens to explain how to enable "Mock Location" were displayed every time the feature was enabled, even if the IVPN was already selected in the developers menu as "Mock Location". This is no longer an issue.

The feature works as expected, tested with both OpenVPN and WireGuard and the GPS's real location was always overridden by the location from the VPN server (when connected). This looks good to go.

**Comment by ivpn786** [comment]
What's the point of issues remaining Open even when they have been implemented?

**Comment by gorkapernas** [comment]
@ivpn786 the issue is in Done status in our workflow which means that the feature has been implemented and deployed, if the ticket does not require more work, the project owner will close it accordingly.
