### ISSUE TITLE
Increase tap area for Settings buttons/actions

### ISSUE THREAD

**Issue by jurajhilje** [ivpn/android-app#242]
Increase tap area for Settings buttons/actions.

E.g.:

<img src="https://github.com/ivpn/android-app/assets/3176222/3c74fb2d-9699-452c-8c9b-25e1d429acaf" width="400">

**Comment by jurajhilje** [comment]
@gorkapernas 
Can you confirm that this is resolved in the latest beta APK, for the following buttons:
- Preffered Port
- WireGuard Details
- Regenerate (WireGuard keys)

**Comment by gorkapernas** [comment]
@jurajhilje the tap are has been increased for the buttons you mention, but only for WireGuard.
"Preferred Port" for OpenVPN still have the same issue, the tap area still small.

**Comment by gorkapernas** [comment]
Verified fixed in version 2.9.0 and 2.10.0, the tap area has been increased for the buttons Preferred Port (OpenVPN and WireGuard), WireGuard Details and Regenerate (WireGuard keys).
